name: subrepo-push-dist
on:
  push:
    branches: [main]
    paths:
      - "dist/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install git-subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/.git-subrepo
          source ~/.git-subrepo/.rc
          git subrepo --version

      - name: Set up Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Pull (to integrate) then push
        run: |
          set -e
          # Ensure .gitrepo tracks our own repo's dist branch
          git subrepo pull dist -b dist -r "$(git remote get-url origin)" -u || true
          git subrepo push dist -b dist -r "$(git remote get-url origin)"
